/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Product {
  available_from?: string;
  available_to?: string;
  brand?: {
    created_at?: string;
    description?: string;
    id?: number;
    name?: string;
    seo_meta_description?: string;
    seo_page_title?: string;
    seo_title?: string;
    template?: string;
    updated_at?: string;
  };
  brand_id?: number;
  category_links?: {
    category_id?: number;
    category_sort?: number;
    created_at?: string;
    product_id?: number;
    product_sort?: number;
    updated_at?: string;
  };
  created_at?: string;
  description?: string;
  features?: {
    [x: string]: string[];
  };
  id?: number;
  image_links?: {
    caption?: string;
    filename?: string;
    image_id?: number;
    product_id?: number;
    sort?: number;
  };
  information?: string;
  keywords?: string;
  name?: string;
  order_limit?: number;
  order_limit_min?: number;
  parcel_type?: string;
  price?: number;
  product_code?: string;
  purchasable_from?: string;
  purchase_price?: number;
  seo_meta_description?: string;
  seo_page_title?: string;
  seo_title?: string;
  stock_item?: {
    backorder_enabled?: false;
    backorder_estimate?: string;
    balance?: number;
    balance_alert?: false;
    balance_limit?: number;
    barcode?: string;
    code?: string;
    created_at?: string;
    enabled?: true;
    id?: number;
    location?: string;
    product_id?: number;
    quantity?: number;
    reserved?: number;
    updated_at?: string;
    variation_id?: number;
  };
  supplier_code?: string;
  supplier_id?: number;
  translations?: {
    description?: string;
    information?: string;
    language?: string;
    name?: string;
    seo_meta_description?: string;
    seo_page_title?: string;
    seo_title?: string;
  } | {
    description?: string;
    information?: string;
    language?: string;
    name?: string;
    seo_meta_description?: string;
    seo_page_title?: string;
    seo_title?: string;
  };
  updated_at?: string;
  variations?: ProductVariation[];
  vat_rate?: number;
  visibilities?: {
    is_visible?: true;
    version_id?: number;
  } | {
    is_visible?: false;
    version_id?: number;
  };
  visible_from?: string;
  warranty?: number;
  weight?: number;
}

export interface ProductVariation {
  created_at?: string;
  features?: {
    [x: string]: string[];
  };
  id?: number;
  image_id?: number;
  name?: string;
  price?: number;
  product_code?: string;
  product_id?: number;
  purchase_price?: number;
  sort?: number;
  stock_item?: {
    backorder_enabled?: false;
    backorder_estimate?: string;
    balance?: number;
    balance_alert?: false;
    balance_limit?: number;
    barcode?: string;
    code?: string;
    created_at?: string;
    enabled?: true;
    id?: number;
    location?: string;
    product_id?: number;
    quantity?: number;
    reserved?: number;
    updated_at?: string;
    variation_id?: number;
  };
  updated_at?: string;
  weight?: number;
}
