/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface MCFPageMeta {
  item_count?: number;
  page?: number;
  page_count?: number;
  page_size?: number;
}

export interface MCFResponse<T> {
  data?: T;
  meta?: MCFPageMeta;
}
